services:
  postgres:
    image: postgres:16
    container_name: budgeter_postgres
    environment:
      POSTGRES_DB: budgeter
      POSTGRES_USER: khe
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - budgeter_pgdata:/var/lib/postgresql/data

volumes:
  budgeter_pgdata: